// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: resembla.proto
#ifndef GRPC_resembla_2eproto__INCLUDED
#define GRPC_resembla_2eproto__INCLUDED

#include "resembla.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace resembla {
namespace server {

class ResemblaService final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status find(::grpc::ClientContext* context, const ::resembla::server::ResemblaRequest& request, ::resembla::server::ResemblaResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::resembla::server::ResemblaResponse>> Asyncfind(::grpc::ClientContext* context, const ::resembla::server::ResemblaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::resembla::server::ResemblaResponse>>(AsyncfindRaw(context, request, cq));
    }
    virtual ::grpc::Status eval(::grpc::ClientContext* context, const ::resembla::server::ResemblaOnDemandRequest& request, ::resembla::server::ResemblaResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::resembla::server::ResemblaResponse>> Asynceval(::grpc::ClientContext* context, const ::resembla::server::ResemblaOnDemandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::resembla::server::ResemblaResponse>>(AsyncevalRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::resembla::server::ResemblaResponse>* AsyncfindRaw(::grpc::ClientContext* context, const ::resembla::server::ResemblaRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::resembla::server::ResemblaResponse>* AsyncevalRaw(::grpc::ClientContext* context, const ::resembla::server::ResemblaOnDemandRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status find(::grpc::ClientContext* context, const ::resembla::server::ResemblaRequest& request, ::resembla::server::ResemblaResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::resembla::server::ResemblaResponse>> Asyncfind(::grpc::ClientContext* context, const ::resembla::server::ResemblaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::resembla::server::ResemblaResponse>>(AsyncfindRaw(context, request, cq));
    }
    ::grpc::Status eval(::grpc::ClientContext* context, const ::resembla::server::ResemblaOnDemandRequest& request, ::resembla::server::ResemblaResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::resembla::server::ResemblaResponse>> Asynceval(::grpc::ClientContext* context, const ::resembla::server::ResemblaOnDemandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::resembla::server::ResemblaResponse>>(AsyncevalRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::resembla::server::ResemblaResponse>* AsyncfindRaw(::grpc::ClientContext* context, const ::resembla::server::ResemblaRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::resembla::server::ResemblaResponse>* AsyncevalRaw(::grpc::ClientContext* context, const ::resembla::server::ResemblaOnDemandRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_find_;
    const ::grpc::RpcMethod rpcmethod_eval_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status find(::grpc::ServerContext* context, const ::resembla::server::ResemblaRequest* request, ::resembla::server::ResemblaResponse* response);
    virtual ::grpc::Status eval(::grpc::ServerContext* context, const ::resembla::server::ResemblaOnDemandRequest* request, ::resembla::server::ResemblaResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_find : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_find() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_find() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status find(::grpc::ServerContext* context, const ::resembla::server::ResemblaRequest* request, ::resembla::server::ResemblaResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestfind(::grpc::ServerContext* context, ::resembla::server::ResemblaRequest* request, ::grpc::ServerAsyncResponseWriter< ::resembla::server::ResemblaResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_eval : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_eval() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_eval() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status eval(::grpc::ServerContext* context, const ::resembla::server::ResemblaOnDemandRequest* request, ::resembla::server::ResemblaResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesteval(::grpc::ServerContext* context, ::resembla::server::ResemblaOnDemandRequest* request, ::grpc::ServerAsyncResponseWriter< ::resembla::server::ResemblaResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_find<WithAsyncMethod_eval<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_find : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_find() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_find() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status find(::grpc::ServerContext* context, const ::resembla::server::ResemblaRequest* request, ::resembla::server::ResemblaResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_eval : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_eval() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_eval() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status eval(::grpc::ServerContext* context, const ::resembla::server::ResemblaOnDemandRequest* request, ::resembla::server::ResemblaResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_find : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_find() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::resembla::server::ResemblaRequest, ::resembla::server::ResemblaResponse>(std::bind(&WithStreamedUnaryMethod_find<BaseClass>::Streamedfind, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_find() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status find(::grpc::ServerContext* context, const ::resembla::server::ResemblaRequest* request, ::resembla::server::ResemblaResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedfind(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::resembla::server::ResemblaRequest,::resembla::server::ResemblaResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_eval : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_eval() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::StreamedUnaryHandler< ::resembla::server::ResemblaOnDemandRequest, ::resembla::server::ResemblaResponse>(std::bind(&WithStreamedUnaryMethod_eval<BaseClass>::Streamedeval, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_eval() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status eval(::grpc::ServerContext* context, const ::resembla::server::ResemblaOnDemandRequest* request, ::resembla::server::ResemblaResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedeval(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::resembla::server::ResemblaOnDemandRequest,::resembla::server::ResemblaResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_find<WithStreamedUnaryMethod_eval<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_find<WithStreamedUnaryMethod_eval<Service > > StreamedService;
};

}  // namespace server
}  // namespace resembla


#endif  // GRPC_resembla_2eproto__INCLUDED
