# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: resembla.proto for package 'resembla.server'

require 'grpc'
require 'resembla_pb'

module Resembla
  module Server
    module ResemblaService
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'resembla.server.ResemblaService'

        rpc :find, ResemblaRequest, ResemblaResponse
        rpc :eval, ResemblaOnDemandRequest, ResemblaResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
