# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resembla.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resembla.proto',
  package='resembla.server',
  syntax='proto3',
  serialized_pb=_b('\n\x0eresembla.proto\x12\x0fresembla.server\" \n\x0fResemblaRequest\x12\r\n\x05query\x18\x01 \x01(\t\"<\n\x17ResemblaOnDemandRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\ncandidates\x18\x02 \x03(\t\"\x80\x01\n\x10ResemblaResponse\x12\x39\n\x07results\x18\x01 \x03(\x0b\x32(.resembla.server.ResemblaResponse.Result\x1a\x31\n\x06Result\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x32\xb7\x01\n\x0fResemblaService\x12M\n\x04\x66ind\x12 .resembla.server.ResemblaRequest\x1a!.resembla.server.ResemblaResponse\"\x00\x12U\n\x04\x65val\x12(.resembla.server.ResemblaOnDemandRequest\x1a!.resembla.server.ResemblaResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESEMBLAREQUEST = _descriptor.Descriptor(
  name='ResemblaRequest',
  full_name='resembla.server.ResemblaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='resembla.server.ResemblaRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=67,
)


_RESEMBLAONDEMANDREQUEST = _descriptor.Descriptor(
  name='ResemblaOnDemandRequest',
  full_name='resembla.server.ResemblaOnDemandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='resembla.server.ResemblaOnDemandRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='candidates', full_name='resembla.server.ResemblaOnDemandRequest.candidates', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=129,
)


_RESEMBLARESPONSE_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='resembla.server.ResemblaResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='resembla.server.ResemblaResponse.Result.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='resembla.server.ResemblaResponse.Result.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='resembla.server.ResemblaResponse.Result.score', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=260,
)

_RESEMBLARESPONSE = _descriptor.Descriptor(
  name='ResemblaResponse',
  full_name='resembla.server.ResemblaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='resembla.server.ResemblaResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESEMBLARESPONSE_RESULT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=260,
)

_RESEMBLARESPONSE_RESULT.containing_type = _RESEMBLARESPONSE
_RESEMBLARESPONSE.fields_by_name['results'].message_type = _RESEMBLARESPONSE_RESULT
DESCRIPTOR.message_types_by_name['ResemblaRequest'] = _RESEMBLAREQUEST
DESCRIPTOR.message_types_by_name['ResemblaOnDemandRequest'] = _RESEMBLAONDEMANDREQUEST
DESCRIPTOR.message_types_by_name['ResemblaResponse'] = _RESEMBLARESPONSE

ResemblaRequest = _reflection.GeneratedProtocolMessageType('ResemblaRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESEMBLAREQUEST,
  __module__ = 'resembla_pb2'
  # @@protoc_insertion_point(class_scope:resembla.server.ResemblaRequest)
  ))
_sym_db.RegisterMessage(ResemblaRequest)

ResemblaOnDemandRequest = _reflection.GeneratedProtocolMessageType('ResemblaOnDemandRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESEMBLAONDEMANDREQUEST,
  __module__ = 'resembla_pb2'
  # @@protoc_insertion_point(class_scope:resembla.server.ResemblaOnDemandRequest)
  ))
_sym_db.RegisterMessage(ResemblaOnDemandRequest)

ResemblaResponse = _reflection.GeneratedProtocolMessageType('ResemblaResponse', (_message.Message,), dict(

  Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
    DESCRIPTOR = _RESEMBLARESPONSE_RESULT,
    __module__ = 'resembla_pb2'
    # @@protoc_insertion_point(class_scope:resembla.server.ResemblaResponse.Result)
    ))
  ,
  DESCRIPTOR = _RESEMBLARESPONSE,
  __module__ = 'resembla_pb2'
  # @@protoc_insertion_point(class_scope:resembla.server.ResemblaResponse)
  ))
_sym_db.RegisterMessage(ResemblaResponse)
_sym_db.RegisterMessage(ResemblaResponse.Result)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class ResemblaServiceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.find = channel.unary_unary(
          '/resembla.server.ResemblaService/find',
          request_serializer=ResemblaRequest.SerializeToString,
          response_deserializer=ResemblaResponse.FromString,
          )
      self.eval = channel.unary_unary(
          '/resembla.server.ResemblaService/eval',
          request_serializer=ResemblaOnDemandRequest.SerializeToString,
          response_deserializer=ResemblaResponse.FromString,
          )


  class ResemblaServiceServicer(object):

    def find(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def eval(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ResemblaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'find': grpc.unary_unary_rpc_method_handler(
            servicer.find,
            request_deserializer=ResemblaRequest.FromString,
            response_serializer=ResemblaResponse.SerializeToString,
        ),
        'eval': grpc.unary_unary_rpc_method_handler(
            servicer.eval,
            request_deserializer=ResemblaOnDemandRequest.FromString,
            response_serializer=ResemblaResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'resembla.server.ResemblaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaResemblaServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def find(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def eval(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaResemblaServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def find(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    find.future = None
    def eval(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    eval.future = None


  def beta_create_ResemblaService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('resembla.server.ResemblaService', 'eval'): ResemblaOnDemandRequest.FromString,
      ('resembla.server.ResemblaService', 'find'): ResemblaRequest.FromString,
    }
    response_serializers = {
      ('resembla.server.ResemblaService', 'eval'): ResemblaResponse.SerializeToString,
      ('resembla.server.ResemblaService', 'find'): ResemblaResponse.SerializeToString,
    }
    method_implementations = {
      ('resembla.server.ResemblaService', 'eval'): face_utilities.unary_unary_inline(servicer.eval),
      ('resembla.server.ResemblaService', 'find'): face_utilities.unary_unary_inline(servicer.find),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ResemblaService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('resembla.server.ResemblaService', 'eval'): ResemblaOnDemandRequest.SerializeToString,
      ('resembla.server.ResemblaService', 'find'): ResemblaRequest.SerializeToString,
    }
    response_deserializers = {
      ('resembla.server.ResemblaService', 'eval'): ResemblaResponse.FromString,
      ('resembla.server.ResemblaService', 'find'): ResemblaResponse.FromString,
    }
    cardinalities = {
      'eval': cardinality.Cardinality.UNARY_UNARY,
      'find': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'resembla.server.ResemblaService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
